# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTemplate < Formula
  desc ""
  homepage "https://github.com/Yakiyo/go-template"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Yakiyo/go-template/releases/download/v0.1.1/go-template_Darwin_x86_64.tar.gz"
      sha256 "fdbda5f8108d0d3b7312aee48562eb4caa3f3edab15aff14a987c3725dc01ce2"

      def install
        bin.install "go-template"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Yakiyo/go-template/releases/download/v0.1.1/go-template_Darwin_arm64.tar.gz"
      sha256 "abaa7677a5001b23f7d4dcf9d08df1ba27b5edfd238bb3cd1e77fa03906e4756"

      def install
        bin.install "go-template"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yakiyo/go-template/releases/download/v0.1.1/go-template_Linux_arm64.tar.gz"
      sha256 "7e872a38ed49897d2268c11394b6920efc5d7490dfb39c621e67d121e86d81d4"

      def install
        bin.install "go-template"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Yakiyo/go-template/releases/download/v0.1.1/go-template_Linux_x86_64.tar.gz"
      sha256 "91746845bc62bffc0130a82f19b2946c630db2174b358833c7f2be1919b12d07"

      def install
        bin.install "go-template"
      end
    end
  end
end
