# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gom < Formula
  desc ""
  homepage "https://github.com/Yakiyo/gom"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Yakiyo/gom/releases/download/v0.0.1/gom_Darwin_x86_64.tar.gz"
      sha256 "c07fd06d0b3478c6ec878d2c5ac0fb2209d95ac7cbe0b2fd6b45f317b0817dfb"

      def install
        bin.install "gom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Yakiyo/gom/releases/download/v0.0.1/gom_Darwin_arm64.tar.gz"
      sha256 "68973f66c3c4df03214dead791aadf9a4feb3f92d03271e7e652c72e82b77bbd"

      def install
        bin.install "gom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Yakiyo/gom/releases/download/v0.0.1/gom_Linux_x86_64.tar.gz"
      sha256 "45dda1dfe121b6e0f9c2935456fafc6207f0e3b78f26df3492d9b91b80540261"

      def install
        bin.install "gom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yakiyo/gom/releases/download/v0.0.1/gom_Linux_arm64.tar.gz"
      sha256 "12e06851016871c62a19b1b16f64c7e5f60d3075747dabdf2664c66b236c22f3"

      def install
        bin.install "gom"
      end
    end
  end
end
