# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gon < Formula
  desc ""
  homepage "https://github.com/Yakiyo/gon"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Yakiyo/gon/releases/download/v1.0.0/gon_Darwin_arm64.tar.gz"
      sha256 "b27822166454d5b4cd02c5605df3db6725b2b35eb08adeebe41091cf3db64274"

      def install
        bin.install "gon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Yakiyo/gon/releases/download/v1.0.0/gon_Darwin_x86_64.tar.gz"
      sha256 "0f36e453fd3915a96ce4fabdd25bc3cc46f3241005ceff7e87f42b7c432b1e93"

      def install
        bin.install "gon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yakiyo/gon/releases/download/v1.0.0/gon_Linux_arm64.tar.gz"
      sha256 "a9c25dbc86414da0c233fb06e3512dc033177e23ede630d226411f285afa4c8e"

      def install
        bin.install "gon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Yakiyo/gon/releases/download/v1.0.0/gon_Linux_x86_64.tar.gz"
      sha256 "8fbdb4085e5bba871e5608b58145d1f2a9b6ee6ffa704add934d593a511c868b"

      def install
        bin.install "gon"
      end
    end
  end
end
